### ISSUE TITLE
About cross-domain experiment from miniImageNet to CUB

### ISSUE THREAD

**Issue by lsgn12138** [imtiazziko/LaplacianShot#5]
Hello, I use the model trained with miniImageNet and use it to test CUB, but I got the 72.26 for 1 shot and 82.26 for 5 shot  with CL2N. It is far from the results you report in your paper(55.46 for 1 shot and 66.33 for 5 shot).  The model weight comes from the file you uploaded. The dictionary is models/mini/softmax/resnet18.  Is there anything wrong with my experimental setup?

**Comment by imtiazziko** [comment]
Hi @lsgn12138, What I am guessing is you are using the features extracted for miniImagenet instead of CUB dataset. Could you please check the features from the models (saved as best and last in the corresponding result directory) is for CUB dataset? I guess you are utilizing the saved extracted features for mini Imagenet which is why the result is almost the same as the results for Mini Imagenet with resnet 18. Let me know. Thanks
